### ISSUE TITLE
no data_config.json

### ISSUE THREAD

**Issue by huckiyang** [zhen-he/tracking-by-animation#14]
Dear @zhen-he 

I got an error - seem like related to the reading of data_config.json in the line 80 of the `run.py`
Do we suppose to generate the file of data_config.json before the line 80 or we should put into the root?

> Traceback (most recent call last):
>   File "run.py", line 85, in <module>
>     o.exp_config = utils.load_json('modules/exp_config.json')[o.exp]
>   File "/home/yang/huckcode/tracking-by-animation-master/modules/utils.py", line 57, in load_json
>     data = json.load(f)
>   File "/opt/conda/envs/test1/lib/python3.7/json/__init__.py", line 296, in load
>     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>   File "/opt/conda/envs/test1/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/opt/conda/envs/test1/lib/python3.7/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/opt/conda/envs/test1/lib/python3.7/json/decoder.py", line 353, in raw_decode
>     obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 1 (char 175)

**Comment by zhen-he** [comment]
Hi @huckiyang,

The `data_config.json` contains hyper-parameters related to the data itself, and is generated along with the data.

To generate `data_config.json`, you need to run `gen_mnist.py` or `gen_sprite.py` or `gen_duke.py` first (please see Section 3.1 of the README), where the last line `utils.save_json(data_config, path.join(output_dir, 'data_config.json'))` generates `data_config.json`.

**Comment by huckiyang** [comment]
Hi @zhen-he thanks - I did generate the data but found out there is a format error on the json file.
I follow this https://github.com/StudentWong/tracking-by-animation/commit/45dc6795eabe110aa609606e2af30dd12f8db7da and the issue is resolved. 
Thank you again for the fast reply.

**Comment by zhen-he** [comment]
Thanks for reporting the issue.
