### ISSUE TITLE
Training Model on New Datasets

### ISSUE THREAD

**Issue by jasonkena** [zhen-he/tracking-by-animation#15]
How would I be able to do this? What pre-processing steps should I take?
Thanks

**Comment by zhen-he** [comment]
If you want to use the dataset with static backgrounds (similar to DukeMTMC), you can refer to our pre-processing steps used for DukeMTMC (please see Section 3.1 of the `README.md`). But you might need some modification based on your dataset.

**Comment by jasonkena** [comment]
How do I setup training for plain AVI/MP4 files?

**Comment by zhen-he** [comment]
The first step is to convert the video into `.jpg` files. You can refer to `scripts/mts2jpg.sh`, where we use the `ffmpeg` to convert `.mts` files into `.jpg` files (see line 16). I'm not sure whether ffmpeg works for `.avi` or `.mp4`, but you could have a try. However, there're many alternative ways if it doesn't work.

**Comment by jasonkena** [comment]
I'll try it out. Thank you very much
