### ISSUE TITLE
how to use dukeMTMC dataset

### ISSUE THREAD

**Issue by 756537479** [zhen-he/tracking-by-animation#6]
I want to run gen_duke.py , but i don't know how to move dukeMTMC to path 'data/duke/processed'.
dukeMTMC
|——detections
|——videos
|——ground_truth
...
these dirs how to replace project data dirs , thanks very much
project/data/duke/processed
|——input_roi
|——input
|——bb
|——bg

**Comment by zhen-he** [comment]
I have uploaded the scripts for preprocessing the DukeMTMC. Please see the README and try.

**Comment by 756537479** [comment]
I looked it. Thanks very much.
